# Generated by Django 4.0.4 on 2022-07-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Nombre Ciudad')),
                ('equipo', models.CharField(max_length=50, verbose_name='Nombre Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equios_nba',
                'ordering': ['ciudad', '-equipo'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogNba.equipos'),
        ),
    ]
